"""Update schema

Revision ID: e3ce557bfe56
Revises: 4217e6c3d397
Create Date: 2026-07-09 08:28:44.929462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3ce557bfe56'
down_revision: Union[str, Sequence[str], None] = '4217e6c3d397'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity_logs', 'details',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index('ix_activity_logs_created_at', 'activity_logs', ['created_at'], unique=False)
    op.create_index('ix_activity_logs_entity_type', 'activity_logs', ['entity_type'], unique=False)
    op.create_index('ix_activity_logs_user_id', 'activity_logs', ['user_id'], unique=False)
    op.drop_constraint('activity_logs_user_id_fkey', 'activity_logs', type_='foreignkey')
    op.create_foreign_key(None, 'activity_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_chat_history_created_at', 'chat_history', ['created_at'], unique=False)
    op.create_index('ix_chat_history_user_id', 'chat_history', ['user_id'], unique=False)
    op.drop_constraint('chat_history_user_id_fkey', 'chat_history', type_='foreignkey')
    op.create_foreign_key(None, 'chat_history', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_notifications_is_read', 'notifications', ['is_read'], unique=False)
    op.create_index('ix_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.drop_constraint('notifications_user_id_fkey', 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_project_assignments_project_id', 'project_assignments', ['project_id'], unique=False)
    op.create_index('ix_project_assignments_user_id', 'project_assignments', ['user_id'], unique=False)
    op.create_unique_constraint('uq_project_assignment', 'project_assignments', ['user_id', 'project_id'])
    op.drop_constraint('project_assignments_user_id_fkey', 'project_assignments', type_='foreignkey')
    op.drop_constraint('project_assignments_project_id_fkey', 'project_assignments', type_='foreignkey')
    op.create_foreign_key(None, 'project_assignments', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'project_assignments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_projects_status', 'projects', ['status'], unique=False)
    op.alter_column('reports', 'tasks_completed',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('reports', 'tasks_planned',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('reports', 'blockers',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('reports', 'notes',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('reports', 'links',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index('ix_reports_project_id', 'reports', ['project_id'], unique=False)
    op.create_index('ix_reports_status', 'reports', ['status'], unique=False)
    op.create_index('ix_reports_user_id', 'reports', ['user_id'], unique=False)
    op.create_index('ix_reports_week_start', 'reports', ['week_start'], unique=False)
    op.drop_constraint('reports_user_id_fkey', 'reports', type_='foreignkey')
    op.drop_constraint('reports_project_id_fkey', 'reports', type_='foreignkey')
    op.create_foreign_key(None, 'reports', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'reports', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_index('ix_users_is_active', 'users', ['is_active'], unique=False)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index('ix_users_is_active', table_name='users')
    op.drop_column('users', 'is_active')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.create_foreign_key('reports_project_id_fkey', 'reports', 'projects', ['project_id'], ['id'])
    op.create_foreign_key('reports_user_id_fkey', 'reports', 'users', ['user_id'], ['id'])
    op.drop_index('ix_reports_week_start', table_name='reports')
    op.drop_index('ix_reports_user_id', table_name='reports')
    op.drop_index('ix_reports_status', table_name='reports')
    op.drop_index('ix_reports_project_id', table_name='reports')
    op.alter_column('reports', 'links',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('reports', 'notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('reports', 'blockers',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('reports', 'tasks_planned',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('reports', 'tasks_completed',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_index('ix_projects_status', table_name='projects')
    op.drop_constraint(None, 'project_assignments', type_='foreignkey')
    op.drop_constraint(None, 'project_assignments', type_='foreignkey')
    op.create_foreign_key('project_assignments_project_id_fkey', 'project_assignments', 'projects', ['project_id'], ['id'])
    op.create_foreign_key('project_assignments_user_id_fkey', 'project_assignments', 'users', ['user_id'], ['id'])
    op.drop_constraint('uq_project_assignment', 'project_assignments', type_='unique')
    op.drop_index('ix_project_assignments_user_id', table_name='project_assignments')
    op.drop_index('ix_project_assignments_project_id', table_name='project_assignments')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key('notifications_user_id_fkey', 'notifications', 'users', ['user_id'], ['id'])
    op.drop_index('ix_notifications_user_id', table_name='notifications')
    op.drop_index('ix_notifications_is_read', table_name='notifications')
    op.drop_constraint(None, 'chat_history', type_='foreignkey')
    op.create_foreign_key('chat_history_user_id_fkey', 'chat_history', 'users', ['user_id'], ['id'])
    op.drop_index('ix_chat_history_user_id', table_name='chat_history')
    op.drop_index('ix_chat_history_created_at', table_name='chat_history')
    op.drop_constraint(None, 'activity_logs', type_='foreignkey')
    op.create_foreign_key('activity_logs_user_id_fkey', 'activity_logs', 'users', ['user_id'], ['id'])
    op.drop_index('ix_activity_logs_user_id', table_name='activity_logs')
    op.drop_index('ix_activity_logs_entity_type', table_name='activity_logs')
    op.drop_index('ix_activity_logs_created_at', table_name='activity_logs')
    op.alter_column('activity_logs', 'details',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
